-- TalentPulse synthetic analytics lab. Every object lives in its own schema.
CREATE SCHEMA IF NOT EXISTS talentpulse;
SET search_path TO talentpulse, public;

CREATE TABLE IF NOT EXISTS dim_users (
  user_id integer PRIMARY KEY,
  market text NOT NULL,
  device_type text NOT NULL CHECK (device_type IN ('desktop','mobile','tablet')),
  user_type text NOT NULL CHECK (user_type IN ('new','returning')),
  experience_level text NOT NULL,
  preferred_role text NOT NULL,
  preferred_location text NOT NULL,
  registration_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_jobs (
  job_id integer PRIMARY KEY,
  job_category text NOT NULL,
  job_title text NOT NULL,
  market text NOT NULL,
  location text NOT NULL,
  salary_min integer NOT NULL CHECK (salary_min > 0),
  salary_max integer NOT NULL CHECK (salary_max >= salary_min),
  remote_type text NOT NULL,
  experience_level text NOT NULL,
  posted_date date NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_date (
  date date PRIMARY KEY,
  day_of_week integer NOT NULL,
  day_name text NOT NULL,
  week_start date NOT NULL,
  month integer NOT NULL,
  is_weekend boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_releases (
  release_id text PRIMARY KEY,
  release_name text NOT NULL,
  feature text NOT NULL,
  release_date date NOT NULL,
  market text NOT NULL,
  platform text NOT NULL,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS dim_experiments (
  experiment_id text PRIMARY KEY,
  experiment_name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  primary_metric text NOT NULL,
  assignment_unit text NOT NULL,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS fact_experiment_assignments (
  experiment_id text NOT NULL REFERENCES dim_experiments(experiment_id),
  user_id integer NOT NULL REFERENCES dim_users(user_id),
  variant text NOT NULL CHECK (variant IN ('control','gpt4o','ollama')),
  assigned_at timestamptz NOT NULL,
  PRIMARY KEY (experiment_id,user_id)
);

CREATE TABLE IF NOT EXISTS fact_sessions (
  session_id bigint PRIMARY KEY,
  user_id integer NOT NULL REFERENCES dim_users(user_id),
  job_id integer NOT NULL REFERENCES dim_jobs(job_id),
  occurred_at timestamptz NOT NULL,
  date date NOT NULL REFERENCES dim_date(date),
  market text NOT NULL,
  device_type text NOT NULL,
  user_type text NOT NULL,
  job_category text NOT NULL,
  traffic_source text NOT NULL,
  experience_level text NOT NULL,
  variant text NOT NULL CHECK (variant IN ('control','gpt4o','ollama')),
  search_completed boolean NOT NULL,
  job_viewed boolean NOT NULL,
  apply_clicked boolean NOT NULL,
  application_started boolean NOT NULL,
  cv_uploaded boolean NOT NULL,
  application_submitted boolean NOT NULL,
  application_error boolean NOT NULL,
  load_time_ms integer NOT NULL CHECK (load_time_ms >= 0),
  model_cost_usd numeric(12,6) NOT NULL DEFAULT 0,
  search_result_count integer NOT NULL,
  session_date date GENERATED ALWAYS AS (date) STORED,
  search_performed boolean GENERATED ALWAYS AS (true) STORED,
  result_clicked boolean GENERATED ALWAYS AS (job_viewed) STORED,
  application_completed boolean GENERATED ALWAYS AS (application_submitted) STORED,
  search_latency_ms integer GENERATED ALWAYS AS (load_time_ms) STORED,
  CHECK (NOT job_viewed OR search_completed),
  CHECK (NOT apply_clicked OR job_viewed),
  CHECK (NOT application_started OR apply_clicked),
  CHECK (NOT cv_uploaded OR application_started),
  CHECK (NOT application_submitted OR cv_uploaded),
  CHECK (NOT application_error OR application_started),
  CHECK (NOT (application_submitted AND application_error))
);
CREATE INDEX IF NOT EXISTS idx_sessions_date_market ON fact_sessions(date,market);
CREATE INDEX IF NOT EXISTS idx_sessions_user_date ON fact_sessions(user_id,date);

CREATE TABLE IF NOT EXISTS fact_events (
  event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_seq smallint NOT NULL,
  user_id integer NOT NULL REFERENCES dim_users(user_id),
  session_id bigint NOT NULL REFERENCES fact_sessions(session_id),
  job_id integer REFERENCES dim_jobs(job_id),
  occurred_at timestamptz NOT NULL,
  timestamp timestamptz GENERATED ALWAYS AS (occurred_at) STORED,
  date date NOT NULL REFERENCES dim_date(date),
  event_name text NOT NULL CHECK (event_name IN (
    'search_started','search_completed','search_result_viewed','job_viewed',
    'recommendation_viewed','recommendation_clicked','apply_clicked',
    'application_started','cv_uploaded','application_step_completed',
    'application_submitted','application_error')),
  market text NOT NULL,
  device_type text NOT NULL,
  traffic_source text NOT NULL,
  experiment_id text REFERENCES dim_experiments(experiment_id),
  experiment_variant text NOT NULL,
  page text NOT NULL,
  error_code text,
  load_time_ms integer NOT NULL,
  result_position smallint,
  UNIQUE (session_id,event_seq)
);
CREATE INDEX IF NOT EXISTS idx_events_date_name ON fact_events(date,event_name);

CREATE TABLE IF NOT EXISTS fact_applications (
  application_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES dim_users(user_id),
  session_id bigint NOT NULL UNIQUE REFERENCES fact_sessions(session_id),
  job_id integer NOT NULL REFERENCES dim_jobs(job_id),
  started_at timestamptz NOT NULL,
  submitted_at timestamptz,
  status text NOT NULL CHECK (status IN ('submitted','abandoned','error')),
  market text NOT NULL,
  device_type text NOT NULL,
  error_code text,
  CHECK (submitted_at IS NULL OR submitted_at >= started_at)
);

-- One Bernoulli outcome per assigned user in a predeclared experiment window.
CREATE TABLE IF NOT EXISTS fact_experiment_outcomes (
  experiment_id text NOT NULL,
  user_id integer NOT NULL,
  variant text NOT NULL CHECK (variant IN ('control','gpt4o','ollama')),
  window_start date NOT NULL,
  window_end date NOT NULL,
  exposed boolean NOT NULL,
  converted boolean NOT NULL,
  job_engaged boolean NOT NULL,
  sessions integer NOT NULL,
  errors integer NOT NULL,
  avg_load_time_ms double precision NOT NULL,
  model_cost_usd numeric(12,6) NOT NULL,
  PRIMARY KEY (experiment_id,user_id),
  FOREIGN KEY (experiment_id,user_id) REFERENCES fact_experiment_assignments(experiment_id,user_id),
  CHECK (NOT converted OR exposed),
  CHECK (NOT job_engaged OR exposed)
);

-- Live calls are recorded separately from synthetic historical experiment data.
CREATE TABLE IF NOT EXISTS fact_search_runs (
  run_id text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  query text NOT NULL,
  market text NOT NULL,
  variant text NOT NULL,
  provider text NOT NULL,
  model text,
  status text NOT NULL,
  -- Not-configured, no-candidate and rate-limited runs have no measured latency.
  latency_ms integer,
  -- Provider responses may omit billing; unknown live cost must remain NULL.
  cost_usd numeric(12,6),
  error_message text,
  synthetic boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS fact_search_results (
  run_id text NOT NULL REFERENCES fact_search_runs(run_id) ON DELETE CASCADE,
  job_id integer NOT NULL REFERENCES dim_jobs(job_id),
  rank integer NOT NULL,
  score double precision,
  explanation text,
  PRIMARY KEY (run_id,rank)
);

CREATE TABLE IF NOT EXISTS api_usage_daily (
  day date NOT NULL,
  client_hash text NOT NULL,
  requests integer NOT NULL DEFAULT 0,
  PRIMARY KEY (day,client_hash)
);
CREATE TABLE IF NOT EXISTS live_search_calls (
  call_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  query text NOT NULL,
  provider text NOT NULL,
  model text,
  status text NOT NULL,
  latency_ms integer NOT NULL,
  cost_usd numeric(12,6) NOT NULL DEFAULT 0,
  job_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  error_code text
);

CREATE TABLE IF NOT EXISTS fact_kpis (
  date date NOT NULL REFERENCES dim_date(date),
  market text NOT NULL,
  sessions integer NOT NULL,
  active_users integer NOT NULL,
  searches integer NOT NULL,
  job_views integer NOT NULL,
  application_starts integer NOT NULL,
  completed_applications integer NOT NULL,
  errors integer NOT NULL,
  PRIMARY KEY (date,market)
);

CREATE TABLE IF NOT EXISTS seed_manifest (
  seed_version text PRIMARY KEY,
  seed integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  users integer NOT NULL,
  jobs integer NOT NULL,
  sessions integer NOT NULL,
  events bigint NOT NULL,
  synthetic boolean NOT NULL DEFAULT true
);

CREATE OR REPLACE VIEW powerbi_daily_kpis AS
SELECT date, market, count(*)::integer AS sessions,
       count(DISTINCT user_id)::integer AS active_users,
       count(*) FILTER (WHERE search_completed)::integer AS completed_searches,
       count(*) FILTER (WHERE job_viewed)::integer AS job_views,
       count(*) FILTER (WHERE application_started)::integer AS application_starts,
       count(*) FILTER (WHERE application_submitted)::integer AS applications,
       count(*) FILTER (WHERE application_error)::integer AS errors,
       avg(load_time_ms)::numeric(10,2) AS average_load_time_ms,
       count(*) FILTER (WHERE application_submitted)::numeric / nullif(count(*),0) AS application_conversion,
       count(*) FILTER (WHERE application_submitted)::numeric / nullif(count(*) FILTER (WHERE application_started),0) AS completion_rate
FROM fact_sessions GROUP BY date,market;

CREATE OR REPLACE VIEW powerbi_experiment_users AS
SELECT o.*, u.market,u.device_type,u.user_type,u.experience_level
FROM fact_experiment_outcomes o JOIN dim_users u USING(user_id);

CREATE OR REPLACE VIEW powerbi_funnel_segments AS
SELECT date,market,device_type,user_type,job_category,traffic_source,variant,
       count(*)::integer AS searches,
       count(*) FILTER (WHERE job_viewed)::integer AS job_views,
       count(*) FILTER (WHERE apply_clicked)::integer AS apply_clicks,
       count(*) FILTER (WHERE application_started)::integer AS application_starts,
       count(*) FILTER (WHERE cv_uploaded)::integer AS cv_uploads,
       count(*) FILTER (WHERE application_submitted)::integer AS application_submissions
FROM fact_sessions GROUP BY date,market,device_type,user_type,job_category,traffic_source,variant;

CREATE OR REPLACE VIEW bi_daily_kpis AS
SELECT date,market,sessions AS searches,active_users,job_views,application_starts,
       applications AS completed_applications,errors,average_load_time_ms,
       application_conversion,completion_rate
FROM powerbi_daily_kpis;
CREATE OR REPLACE VIEW bi_funnel_segments AS SELECT * FROM powerbi_funnel_segments;
CREATE OR REPLACE VIEW bi_experiment_users AS SELECT * FROM powerbi_experiment_users;
